### ISSUE TITLE
Skin helper backup not working  kodi 18.1 32 bit

### ISSUE THREAD

**Issue by DoBucki** [cartmandos/skin.titan.bingie#31]
Works on tablet 64 but,  transfered to tv box and will not work.  Unistalled added skin only updated and still wouldn't backup skin. 
2019-04-07 02:52:10.633 T:32255   ERROR: NEWADDON Unknown Video Info Key "slug"
2019-04-07 02:52:10.633 T:32255   ERROR: NEWADDON Unknown Video Info Key "tmdb_id"
2019-04-07 02:52:10.633 T:32255   ERROR: NEWADDON Unknown Video Info Key "trakt_id"
2019-04-07 02:52:10.633 T:32255   ERROR: NEWADDON Unknown Video Info Key "tvdb_id"
2019-04-07 02:52:22.031 T:32362  NOTICE: Skin Helper Backup --> Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/default.py", line 30, in __init__
                                                getattr(self, action)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/default.py", line 52, in backup
                                                backuprestore.backup(filters, backup_file, silent_backup)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/resources/lib/backuprestore.py", line 58, in backup
                                                zip_tofile(temp_path, zip_temp)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/resources/lib/utils.py", line 167, in zip_tofile
                                                zip_file = add_tozip(src, zip_file, abs_src)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/resources/lib/utils.py", line 156, in add_tozip
                                                zip_file.write(absname.encode("utf-8"), arcname.encode("utf-8"))
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 1202, in write
                                            IOError: [Errno 22] Invalid argument
2019-04-07 02:52:22.032 T:32362   ERROR: Skin Helper Backup --> ERROR in __main__ ! --> [Errno 22] Invalid argument
2019-04-07 02:52:28.535 T:32156  NOTICE:   load skin from: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/skin.titan.leiabeta.bingie.mode (version: 0.3)
2019-04-07 02:52:30.447 T:32156 WARNING: Skin has invalid include:
2019-04-07 02:52:31.250 T:32356 WARNING: Previous line repeats 14 times.
2019-04-07 02:52:31.250 T:32356   ERROR: Window Translator: Can't find window infodialog
2019-04-07 02:52:37.016 T:32156 WARNING: Trying to add unsupported control type 1
2019-04-07 02:52:41.388 T:350 WARNING: Previous line repeats 20 times.
2019-04-07 02:52:41.389 T:350  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.271
2019-04-07 02:52:42.423 T:350  NOTICE: [B][COLORdarkgrey]SIG-Sauer[/COLOR][/B]: Version: |2018.06.28| Queries: |{'reload': '20190407075101', 'mode': 'show_progress'}|
2019-04-07 02:52:42.424 T:350  NOTICE: [B][COLORdarkgrey]SIG-Sauer[/COLOR][/B]: Args: |['plugin://plugin.video.sigsauer/', '2', '?mode=show_progress&reload=20190407075101', 'resume:false']|
2019-04-07 02:52:44.864 T:350   ERROR: NEWADDON Unknown Video Info Key "imdb_id"
2019-04-07 02:52:44.864 T:350   ERROR: NEWADDON Unknown Video Info Key "slug"
2019-04-07 02:52:44.864 T:350   ERROR: NEWADDON Unknown Video Info Key "tmdb_id"
2019-04-07 02:52:44.864 T:350   ERROR: NEWADDON Unknown Video Info Key "trakt_id"
2019-04-07 02:52:44.864 T:350   ERROR: NEWADDON Unknown Video Info Key "tvdb_id"
2019-04-07 02:52:46.075 T:350   ERROR: NEWADDON Unknown Video Info Key "imdb_id"
2019-04-07 02:52:46.076 T:350   ERROR: NEWADDON Unknown Video Info Key "slug"
2019-04-07 02:52:46.076 T:350   ERROR: NEWADDON Unknown Video Info Key "tmdb_id"
2019-04-07 02:52:46.076 T:350   ERROR: NEWADDON Unknown Video Info Key "trakt_id"
2019-04-07 02:52:46.076 T:350   ERROR: NEWADDON Unknown Video Info Key "tvdb_id"
2019-04-07 02:52:46.437 T:350   ERROR: NEWADDON Unknown

https://paste.ubuntu.com/p/dVGx7kg58V/

**Comment by cartmandos** [comment]
Not skin-related issue AND log contains banned add-ons AND on a custom compiled build of Kodi.

**Comment by DoBucki** [comment]
To be clear the log is from when I reinstalled my backup after fresh kodi and bingie 1.0.1.  I couldn't get my skin backup to work and reinstalled my backup.  I also tried manually updating skin backup files,  (see attached) 
[skin helper service backup 2019-04-07 11.21.28.pdf](https://github.com/cartmandos/skin.titan.bingie/files/3051729/skin.helper.service.backup.2019-04-07.11.21.28.pdf)
