### ISSUE TITLE
Skinhelper not working in kodi 18.1 32 bit, fresh install

### ISSUE THREAD

**Issue by DoBucki** [cartmandos/skin.titan.bingie#32]
Thanks for the quick response earlier.  Duplicated same results on my phone with new kodi install
2019-04-07 12:58:17.621 T:26265  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 56576 m_frames: 3536 m_frameSize: 8 channels: 2
2019-04-07 12:58:32.679 T:27806  NOTICE: Skin Helper Backup --> Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/default.py", line 30, in __init__
                                                getattr(self, action)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/default.py", line 52, in backup
                                                backuprestore.backup(filters, backup_file, silent_backup)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/resources/lib/backuprestore.py", line 58, in backup
                                                zip_tofile(temp_path, zip_temp)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/resources/lib/utils.py", line 167, in zip_tofile
                                                zip_file = add_tozip(src, zip_file, abs_src)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/resources/lib/utils.py", line 156, in add_tozip
                                                zip_file.write(absname.encode("utf-8"), arcname.encode("utf-8"))
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 1202, in write
                                            IOError: [Errno 22] Invalid argument
2019-04-07 12:58:32.679 T:27806   ERROR: Skin Helper Backup --> ERROR in __main__ ! --> [Errno 22] Invalid argument
2019-04-07 12:58:57.312 T:27833   ERROR: Control 11 in window 10101 has been asked to focus, but it can't
2019-04-07 12:58:59.996 T:27833  NOTICE: Skin Helper Backup --> Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/default.py", line 30, in __init__
                                                getattr(self, action)()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/default.py", line 65, in restore
                                                backuprestore.restore(silent)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/resources/lib/backuprestore.py", line 95, in restore
                                                unzip_fromfile(zip_temp, temp_path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.skinbackup/resources/lib/utils.py", line 178, in unzip_fromfile
                                                zip_file = zipfile.ZipFile(zip_path, 'r')
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 770, in __init__
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 811, in _RealGetContents
                                            BadZipfile: File is not a zip file
2019-04-07 12:58:59.996 T:27833   ERROR: Skin Helper Backup --> ERROR in __main__ ! --> File is not a zip file
2019-04-07 12:59:04.622 T:26255   ERROR: Window Translator: Can't find window show
2019-04-07 12:59:30.022 T:27288   ERROR: CCurlFile::Stat - Failed: Timeout was 

https://paste.ubuntu.com/p/dVGx7kg58V/

**Comment by DoBucki** [comment]
When upgrade to 64 bit problem gone but by Android box is only capable of 32 bit

https://paste.kodi.tv/ujuwapakof

**Comment by cartmandos** [comment]
This is a skin helper backup issue which is not skin related. Sorry but can't help you with that.
